name: TWRP Build with Omni

on:
  workflow_dispatch:
    inputs:
      OMNI_BRANCH:
        description: 'Omni manifest branch (e.g., android-12.1)'
        required: true
        default: 'twrp-5.1'
      DEVICE_TREE_URL:
        description: 'URL of your device tree repository'
        required: true
        default: 'https://github.com/kareemwael141-dot/twrptreeh532a1'
      DEVICE_TREE_BRANCH:
        description: 'Branch of your device tree (e.g., android-12.1)'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Path to your device tree (e.g., device/manufacturer/codename)'
        required: true
        default: 'device/infinix/h532_a1'
      DEVICE_NAME:
        description: 'Device codename (e.g., mydevice)'
        required: true
        default: 'h532_a1'
      COMMON_TREE_URL:
        description: 'URL of your common tree repository (optional)'
        required: false
      COMMON_TREE_BRANCH:
        description: 'Branch of your common tree (optional)'
        required: false
      COMMON_PATH:
        description: 'Path to your common tree (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Environment and Install Repo
        run: |
          sudo apt-get update -y
          sudo add-apt-repository -y multiverse
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc rsync python3 bc cpio libtinfo5

          # Install the Repo tool globally
          curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
          chmod a+x /usr/local/bin/repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Initialize Repo and Sync Sources
        run: |
          mkdir twrp-source
          cd twrp-source
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b ${{ github.event.inputs.OMNI_BRANCH }} --depth=1
          repo sync -c --no-clone-bundle --no-tags --force-sync -j$(nproc --all)

      - name: Clone Device and Common Trees
        run: |
          cd twrp-source
          git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} --depth=1 ${{ github.event.inputs.DEVICE_PATH }}
          if [[ ! -z "${{ github.event.inputs.COMMON_TREE_URL }}" ]]; then
            git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.COMMON_TREE_BRANCH }} --depth=1 ${{ github.event.inputs.COMMON_PATH }}
          fi

      - name: Set up ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.event.inputs.DEVICE_NAME }}-${{ github.event.inputs.OMNI_BRANCH }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.event.inputs.DEVICE_NAME }}-

      - name: Build TWRP
        run: |
          cd twrp-source
          export ALLOW_MISSING_DEPENDENCIES=true
          export CCACHE_DIR=~/.ccache
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 50G
          . build/envsetup.sh
          lunch omni_${{ github.event.inputs.DEVICE_NAME }}-eng
          mka recoveryimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-recovery-${{ github.event.inputs.DEVICE_NAME }}
          path: twrp-source/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
